### PR TITLE
Fix image alt text

### PR DESCRIPTION
**Pull request by schnedio**

### CODE REVIEW

**Comment by schnedio** [comment]
Sorry, trying to resume this for a while without luck. But since it became urgent, I’ll try to fix that tomorrow. :)

**Comment by longaraymatheus** [comment]
@schnedio no need to rush. Just checking for an estimation 😃

**Comment by schnedio** [comment]
Thanks. By the way, what do you guys think we merge this and treat the other issue in a separate pull request? :)

**Comment by longaraymatheus** [comment]
Alright, sounds like a plan. I've added a new entry to our Trello backlog to keep track of the remaining work. Thanks @schnedio!

**Pull request merged**
